# Generated by Django 2.0.13 on 2019-06-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190617_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default='defaul.png', null=True, upload_to=''),
        ),
    ]
